# fly.toml app configuration file generated for paperless-home-debug on 2024-10-29T20:01:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sw-broken-pipe-test'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 80
  force_https = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "2s"
  method = "GET"
  path = "/maintenance_with_leaf.svg"
  [http_service.checks.headers]
    Host = "make.logs"

[[vm]]
  size = 'shared-cpu-2x'
